vich_uploader:
    db_driver: orm

    mappings:
       restaurante:
           uri_prefix: /images/restaurante
           upload_destination: '%kernel.project_dir%/public/images/restaurante'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
