controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# reservar_restaurante:
#     path: /restaurante/{id<[^/]+-[^/]+>}/reservar
#     controller: App\Controller\ReservaController::crearReserva
